package domain

import (
	"fmt"
	"strings"
)

// FormatScenarioAsGherkin renders a Scenario as a standalone Gherkin
// Scenario block: any user tags on the line above the title, then the
// Scenario header, then the Given/When/Then sections with And
// continuations. Data tables and doc strings are indented under
// their parent step.
//
// This function does NOT prepend the mandatory @d7:<ID> tag — that
// is the responsibility of d7 export gherkin, which adds it when
// the Scenario leaves the DB. Storing it would let users edit it
// and break the SCEN-XXX mapping the verify loop relies on.
func FormatScenarioAsGherkin(s Scenario) string {
	var b strings.Builder
	writeScenarioBlock(&b, s, "", nil)
	return b.String()
}

// FormatFeatureFile renders a complete Gherkin .feature file for a
// Spec and its Scenarios, ready to be written under
// d7/exports/features/<story>/<spec>.feature.
//
// The output is a one-way export, never re-read by d7 (Clover is the
// source of truth), so it carries a generated-file header. featureTags
// are the inherited ancestor d7 tags (e.g. "d7:EPIC-003",
// "d7:STORY-047") written without the leading @; both godog and
// cucumber-js inherit feature-level tags onto every scenario, which is
// what lets `--tags @d7:STORY-047` select a whole subtree. Each
// scenario additionally carries its own mandatory "@d7:<SCEN-ID>" tag
// — the exact-match key the verification ledger maps runner output by.
func FormatFeatureFile(spec Spec, scenarios []Scenario, featureTags []string) string {
	var b strings.Builder

	b.WriteString("# Generated by `d7 export gherkin` — do not edit.\n")
	fmt.Fprintf(&b, "# Source: %s under %s. Edit the spec in d7, then re-export.\n", spec.ID, spec.StoryID)
	b.WriteString("\n")

	writeTagLine(&b, "", featureTags)
	fmt.Fprintf(&b, "Feature: %s\n", spec.Title)

	for _, sc := range scenarios {
		b.WriteString("\n")
		writeScenarioBlock(&b, sc, "  ", []string{"d7:" + sc.ID})
	}

	return b.String()
}

// writeScenarioBlock renders a single Scenario at the given indent.
// leadingTags are prepended (without the leading @) before the
// Scenario's own user tags on the tag line. indent is the base indent
// for the Scenario header; steps sit one level (two spaces) deeper.
func writeScenarioBlock(b *strings.Builder, s Scenario, indent string, leadingTags []string) {
	tags := make([]string, 0, len(leadingTags)+len(s.Tags))
	tags = append(tags, leadingTags...)
	tags = append(tags, s.Tags...)
	writeTagLine(b, indent, tags)

	fmt.Fprintf(b, "%sScenario: %s\n", indent, s.Title)

	writeSection(b, indent, "Given", s.Given)
	writeSection(b, indent, "When", s.When)
	writeSection(b, indent, "Then", s.Then)
}

// writeTagLine writes a space-separated @tag line at the given indent,
// adding the leading @ to each raw tag. It writes nothing when there
// are no tags.
func writeTagLine(b *strings.Builder, indent string, tags []string) {
	if len(tags) == 0 {
		return
	}
	b.WriteString(indent)
	for i, t := range tags {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString("@")
		b.WriteString(t)
	}
	b.WriteString("\n")
}

// writeSection writes a Given/When/Then section at the given base
// indent. The first step uses the provided keyword; subsequent steps
// use And. Data tables and doc strings are indented under their parent
// step.
func writeSection(b *strings.Builder, indent, keyword string, steps []Step) {
	for i, step := range steps {
		kw := keyword
		if i > 0 {
			kw = "And"
		}
		fmt.Fprintf(b, "%s  %s %s\n", indent, kw, step.Text)

		if step.DocString != nil {
			writeDocString(b, indent, *step.DocString)
		}
		if step.DataTable != nil {
			writeDataTable(b, indent, *step.DataTable)
		}
	}
}

// writeDocString writes a Gherkin doc string block indented under
// its parent step. Each line of the payload is indented to four
// spaces past the base indent; the """ delimiters sit at the same
// depth (one extra indent beyond the step's two spaces). A single
// trailing newline on the payload is stripped so YAML block
// scalars (which preserve a final "\n") do not render a spurious
// blank line before the closing """.
func writeDocString(b *strings.Builder, indent, payload string) {
	payload = strings.TrimSuffix(payload, "\n")
	b.WriteString(indent + "    \"\"\"\n")
	for _, line := range strings.Split(payload, "\n") {
		if line == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString(indent + "    ")
		b.WriteString(line)
		b.WriteString("\n")
	}
	b.WriteString(indent + "    \"\"\"\n")
}

// writeDataTable writes a Gherkin data table indented under its
// parent step. Columns are padded to the widest cell in each
// column so the table is readable.
func writeDataTable(b *strings.Builder, indent string, t DataTable) {
	rows := make([][]string, 0, len(t.Rows)+1)
	if len(t.Headers) > 0 {
		rows = append(rows, t.Headers)
	}
	rows = append(rows, t.Rows...)
	if len(rows) == 0 {
		return
	}

	// Compute per-column widths.
	ncols := 0
	for _, r := range rows {
		if len(r) > ncols {
			ncols = len(r)
		}
	}
	widths := make([]int, ncols)
	for _, r := range rows {
		for i, cell := range r {
			if n := len(cell); n > widths[i] {
				widths[i] = n
			}
		}
	}

	for _, r := range rows {
		b.WriteString(indent + "    ")
		for i := 0; i < ncols; i++ {
			cell := ""
			if i < len(r) {
				cell = r[i]
			}
			if i == 0 {
				b.WriteString("| ")
			}
			fmt.Fprintf(b, "%-*s | ", widths[i], cell)
		}
		b.WriteString("\n")
	}
}
