package domain_test

import (
	"strings"
	"testing"

	"github.com/c64-io/daedalus/internal/core/domain"
)

func TestFormatScenarioAsGherkin_Basic(t *testing.T) {
	t.Parallel()

	s := domain.Scenario{
		ID:     "SCEN-001",
		SpecID: "SPEC-001",
		Title:  "User redeems a valid coupon",
		Given: []domain.Step{
			{Text: `a user has a valid coupon "SAVE10"`},
			{Text: "the coupon has not been redeemed"},
		},
		When: []domain.Step{
			{Text: "the user applies the coupon at checkout"},
		},
		Then: []domain.Step{
			{Text: "the order total is reduced by 10%"},
			{Text: "the coupon is marked as redeemed"},
		},
	}

	got := domain.FormatScenarioAsGherkin(s)
	want := `Scenario: User redeems a valid coupon
  Given a user has a valid coupon "SAVE10"
  And the coupon has not been redeemed
  When the user applies the coupon at checkout
  Then the order total is reduced by 10%
  And the coupon is marked as redeemed
`
	if got != want {
		t.Errorf("gherkin mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestFormatScenarioAsGherkin_WithTags(t *testing.T) {
	t.Parallel()

	s := domain.Scenario{
		ID:    "SCEN-002",
		Title: "Expired coupon is rejected",
		Tags:  []string{"happy-path", "checkout"},
		Given: []domain.Step{{Text: "an expired coupon"}},
		When:  []domain.Step{{Text: "the user applies it"}},
		Then:  []domain.Step{{Text: "the system rejects it"}},
	}

	got := domain.FormatScenarioAsGherkin(s)
	if !strings.HasPrefix(got, "@happy-path @checkout\n") {
		t.Errorf("tag line missing or wrong: %q", got)
	}
	if !strings.Contains(got, "Scenario: Expired coupon is rejected") {
		t.Errorf("title line missing: %q", got)
	}
}

func TestFormatScenarioAsGherkin_OmitsD7Tag(t *testing.T) {
	t.Parallel()

	// Storage must not include @d7:<ID> — it is added at export.
	s := domain.Scenario{
		ID:    "SCEN-003",
		Title: "test",
		Tags:  []string{"smoke"},
		Given: []domain.Step{{Text: "x"}},
		When:  []domain.Step{{Text: "y"}},
		Then:  []domain.Step{{Text: "z"}},
	}
	got := domain.FormatScenarioAsGherkin(s)
	if strings.Contains(got, "@d7:") {
		t.Errorf("output must not contain @d7: tag, got: %s", got)
	}
}

func TestFormatScenarioAsGherkin_DocString(t *testing.T) {
	t.Parallel()

	payload := `{ "status": "ok" }`
	s := domain.Scenario{
		ID:    "SCEN-004",
		Title: "API responds",
		Given: []domain.Step{
			{
				Text:      "the API responds with:",
				DocString: &payload,
			},
		},
		When: []domain.Step{{Text: "the client reads it"}},
		Then: []domain.Step{{Text: "the client parses it"}},
	}

	got := domain.FormatScenarioAsGherkin(s)
	if !strings.Contains(got, "    \"\"\"\n") {
		t.Errorf("doc string delimiters missing: %s", got)
	}
	if !strings.Contains(got, `    { "status": "ok" }`) {
		t.Errorf("doc string payload missing: %s", got)
	}
}

func TestFormatFeatureFile(t *testing.T) {
	t.Parallel()

	spec := domain.Spec{ID: "SPEC-098", StoryID: "STORY-047", Title: "Login rules"}
	scenarios := []domain.Scenario{
		{
			ID:    "SCEN-114",
			Title: "User logs in",
			Tags:  []string{"happy-path"},
			Given: []domain.Step{{Text: "a valid token"}},
			When:  []domain.Step{{Text: "the user signs in"}},
			Then:  []domain.Step{{Text: "they reach the dashboard"}},
		},
		{
			ID:    "SCEN-115",
			Title: "Expired token is rejected",
			Given: []domain.Step{{Text: "an expired token"}},
			When:  []domain.Step{{Text: "the user signs in"}},
			Then:  []domain.Step{{Text: "the request is denied"}},
		},
	}
	tags := []string{"d7:EPIC-003", "d7:FEAT-012", "d7:STORY-047", "d7:SPEC-098"}

	got := domain.FormatFeatureFile(spec, scenarios, tags)
	want := "# Generated by `d7 export gherkin` — do not edit.\n" +
		"# Source: SPEC-098 under STORY-047. Edit the spec in d7, then re-export.\n" +
		"\n" +
		"@d7:EPIC-003 @d7:FEAT-012 @d7:STORY-047 @d7:SPEC-098\n" +
		"Feature: Login rules\n" +
		"\n" +
		"  @d7:SCEN-114 @happy-path\n" +
		"  Scenario: User logs in\n" +
		"    Given a valid token\n" +
		"    When the user signs in\n" +
		"    Then they reach the dashboard\n" +
		"\n" +
		"  @d7:SCEN-115\n" +
		"  Scenario: Expired token is rejected\n" +
		"    Given an expired token\n" +
		"    When the user signs in\n" +
		"    Then the request is denied\n"
	if got != want {
		t.Errorf("feature file mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestFormatFeatureFile_NestedDataTable(t *testing.T) {
	t.Parallel()

	spec := domain.Spec{ID: "SPEC-001", StoryID: "STORY-001", Title: "Users"}
	scenarios := []domain.Scenario{
		{
			ID:    "SCEN-001",
			Title: "Users exist",
			Given: []domain.Step{
				{
					Text: "the following users exist:",
					DataTable: &domain.DataTable{
						Headers: []string{"name"},
						Rows:    [][]string{{"alice"}},
					},
				},
			},
			When: []domain.Step{{Text: "listed"}},
			Then: []domain.Step{{Text: "both appear"}},
		},
	}

	got := domain.FormatFeatureFile(spec, scenarios, []string{"d7:STORY-001", "d7:SPEC-001"})
	// Inside a feature file the step sits at four spaces, so its data
	// table nests one level deeper, at six.
	if !strings.Contains(got, "      | name  |") {
		t.Errorf("nested data table indentation wrong:\n%s", got)
	}
}

func TestFormatScenarioAsGherkin_DataTable(t *testing.T) {
	t.Parallel()

	s := domain.Scenario{
		ID:    "SCEN-005",
		Title: "Users exist",
		Given: []domain.Step{
			{
				Text: "the following users exist:",
				DataTable: &domain.DataTable{
					Headers: []string{"name", "email"},
					Rows: [][]string{
						{"alice", "alice@example.com"},
						{"bob", "bob@example.com"},
					},
				},
			},
		},
		When: []domain.Step{{Text: "the admin lists them"}},
		Then: []domain.Step{{Text: "both appear"}},
	}

	got := domain.FormatScenarioAsGherkin(s)
	if !strings.Contains(got, "| name  | email             |") {
		t.Errorf("data table header missing or misaligned:\n%s", got)
	}
	if !strings.Contains(got, "| alice | alice@example.com |") {
		t.Errorf("data table row missing:\n%s", got)
	}
}
