package service_test

import (
	"context"
	"path/filepath"
	"strings"
	"testing"

	"github.com/c64-io/daedalus/internal/core/domain"
	"github.com/c64-io/daedalus/internal/core/port/driving"
	"github.com/c64-io/daedalus/internal/core/service"
)

// newExportFixture builds an ExportService over in-memory fakes with a
// workspace rooted at /proj, plus the fakeFS so tests can inspect what
// was written.
func newExportFixture(
	specs []domain.Spec,
	scenarios []domain.Scenario,
	stories []domain.Story,
	features []domain.Feature,
	epics []domain.Epic,
) (*service.ExportService, *fakeFS) {
	fs := newFakeFS("/proj")
	fs.existing[filepath.Join("/proj", "d7", ".db")] = true

	svc := service.NewExportService(
		fs,
		&fakeStoryRepo{stories: stories},
		&fakeSpecRepo{specs: specs},
		&fakeScenarioRepo{scenarios: scenarios},
		&fakeFeatureRepo{features: features},
		&fakeEpicRepo{epics: epics},
	)
	return svc, fs
}

func TestExportGherkin_WritesFeatureFiles(t *testing.T) {
	epics := []domain.Epic{{ID: "EPIC-001", IdeaID: "IDEA-001"}}
	features := []domain.Feature{{ID: "FEAT-001", EpicID: "EPIC-001"}}
	stories := []domain.Story{{ID: "STORY-001", FeatureID: "FEAT-001"}}
	specs := []domain.Spec{
		{ID: "SPEC-001", StoryID: "STORY-001", Title: "Login rules"},
		{ID: "SPEC-002", StoryID: "STORY-001", Title: "Empty spec"}, // no scenarios
	}
	scenarios := []domain.Scenario{
		{
			ID: "SCEN-001", SpecID: "SPEC-001", Title: "User logs in",
			Tags:  []string{"happy-path"},
			Given: []domain.Step{{Text: "a valid token"}},
			When:  []domain.Step{{Text: "the user signs in"}},
			Then:  []domain.Step{{Text: "they reach the dashboard"}},
		},
		{
			ID: "SCEN-002", SpecID: "SPEC-001", Title: "Expired token rejected",
			Given: []domain.Step{{Text: "an expired token"}},
			When:  []domain.Step{{Text: "the user signs in"}},
			Then:  []domain.Step{{Text: "the request is denied"}},
		},
	}

	svc, fs := newExportFixture(specs, scenarios, stories, features, epics)

	res, err := svc.ExportGherkin(context.Background(), driving.GherkinExportRequest{})
	if err != nil {
		t.Fatalf("ExportGherkin: %v", err)
	}

	wantDir := filepath.Join("/proj", "d7", "exports", "features")
	if res.FeaturesDir != wantDir {
		t.Errorf("FeaturesDir = %q, want %q", res.FeaturesDir, wantDir)
	}
	if res.ScenarioCount != 2 {
		t.Errorf("ScenarioCount = %d, want 2", res.ScenarioCount)
	}
	wantRel := filepath.Join("STORY-001", "SPEC-001.feature")
	if len(res.Files) != 1 || res.Files[0] != wantRel {
		t.Fatalf("Files = %v, want [%q] (SPEC-002 should be pruned)", res.Files, wantRel)
	}

	abs := filepath.Join(wantDir, wantRel)
	content, ok := fs.files[abs]
	if !ok {
		t.Fatalf("expected file written at %q; files=%v", abs, keysOf(fs.files))
	}
	got := string(content)

	for _, want := range []string{
		"# Generated by `d7 export gherkin`",
		"@d7:EPIC-001 @d7:FEAT-001 @d7:STORY-001 @d7:SPEC-001\nFeature: Login rules\n",
		"  @d7:SCEN-001 @happy-path\n  Scenario: User logs in\n",
		"    Given a valid token\n",
		"  @d7:SCEN-002\n  Scenario: Expired token rejected\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("feature file missing %q\nfull content:\n%s", want, got)
		}
	}

	// The empty SPEC-002 must not produce a file.
	emptyAbs := filepath.Join(wantDir, "STORY-001", "SPEC-002.feature")
	if _, ok := fs.files[emptyAbs]; ok {
		t.Errorf("empty spec SPEC-002 should not have a feature file")
	}
}

func TestExportGherkin_PrunesStaleTree(t *testing.T) {
	stories := []domain.Story{{ID: "STORY-001", FeatureID: "FEAT-001"}}
	features := []domain.Feature{{ID: "FEAT-001", EpicID: "EPIC-001"}}
	epics := []domain.Epic{{ID: "EPIC-001", IdeaID: "IDEA-001"}}
	specs := []domain.Spec{{ID: "SPEC-001", StoryID: "STORY-001", Title: "Rules"}}
	scenarios := []domain.Scenario{{
		ID: "SCEN-001", SpecID: "SPEC-001", Title: "x",
		Given: []domain.Step{{Text: "a"}},
		When:  []domain.Step{{Text: "b"}},
		Then:  []domain.Step{{Text: "c"}},
	}}

	svc, fs := newExportFixture(specs, scenarios, stories, features, epics)

	featuresDir := filepath.Join("/proj", "d7", "exports", "features")
	stale := filepath.Join(featuresDir, "STORY-999", "SPEC-999.feature")
	fs.files[stale] = []byte("stale generated content")

	if _, err := svc.ExportGherkin(context.Background(), driving.GherkinExportRequest{}); err != nil {
		t.Fatalf("ExportGherkin: %v", err)
	}

	if _, ok := fs.files[stale]; ok {
		t.Errorf("stale file %q should have been pruned", stale)
	}
	var sawRemove bool
	for _, p := range fs.removed {
		if p == featuresDir {
			sawRemove = true
		}
	}
	if !sawRemove {
		t.Errorf("features dir %q was not removed; removed=%v", featuresDir, fs.removed)
	}
}

func TestExportGherkin_NoScenarios(t *testing.T) {
	specs := []domain.Spec{{ID: "SPEC-001", StoryID: "STORY-001", Title: "Rules"}}
	stories := []domain.Story{{ID: "STORY-001", FeatureID: "FEAT-001"}}

	svc, fs := newExportFixture(specs, nil, stories, nil, nil)

	res, err := svc.ExportGherkin(context.Background(), driving.GherkinExportRequest{})
	if err != nil {
		t.Fatalf("ExportGherkin: %v", err)
	}
	if len(res.Files) != 0 || res.ScenarioCount != 0 {
		t.Errorf("expected empty export, got Files=%v ScenarioCount=%d", res.Files, res.ScenarioCount)
	}
	// The features directory should still be (re)created.
	featuresDir := filepath.Join("/proj", "d7", "exports", "features")
	if _, ok := fs.created[featuresDir]; !ok {
		t.Errorf("features dir %q should be created even with no scenarios", featuresDir)
	}
}

func TestExportGherkin_WorkspaceNotFound(t *testing.T) {
	fs := newFakeFS("/proj") // no .db marked existing
	svc := service.NewExportService(
		fs, &fakeStoryRepo{}, &fakeSpecRepo{}, &fakeScenarioRepo{},
		&fakeFeatureRepo{}, &fakeEpicRepo{},
	)
	if _, err := svc.ExportGherkin(context.Background(), driving.GherkinExportRequest{}); err == nil {
		t.Fatal("expected error when workspace is missing")
	}
}

func keysOf(m map[string][]byte) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
